
[meta]
name = "DialogUI-MCDR"
author = [{ github = "Mooling0602" }]
maintainers = []
description = "Provides dialog UI for MCDR and its plugins using managed Minecraft datapacks."
main-branch = "main"
license = "GPL-3.0"

[platform]
remote-hoster = [{ github = "https://github.com" }]
